### ISSUE TITLE
Safe `BlockHeader` Decoding

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/chainweb-node#104]
#322 removes recently added logic that detects when a genesis block is being decoded. This caused problems for code reorganization, [as described here](https://github.com/kadena-io/chainweb/pull/322#discussion_r262168553).

Some logic of similar spirit ought to be reinstated somewhere. The primary consumer of the function in question (`decodeBlockHeader`) is the `FromJSON` instance of `BlockHeader`. Currently, the dependency graph between these types and functions is as follows:

![genesisblockheader](https://user-images.githubusercontent.com/229679/53760951-24bf6a00-3e79-11e9-8ca5-054e8645f153.png)

To put the check back where it was would require drawing an arrow between `decodeBlockHeader` and `genesisBlockHeader`, which is clearly not possible. So, some further consideration is required.

**Comment by mercadoa** [comment]
Need Colin/Lars to opine on whether this is still needed

**Comment by mercadoa** [comment]
Moved issue over to chainweb-node (104)

**Comment by chessai** [comment]
I don't believe this is relevant any longer.
