### ISSUE TITLE
vulnerability?

### ISSUE THREAD

**Issue by dataf3l** [kadena-io/chainweb-node#1143]
my server is getting request like this one:

51.159.23.89 - - [02/Sep/2020:03:45:19 +0000] "GET /chainweb/0.0/mainnet01/cut HTTP/1.1" 404 152 "-" "python-httpx/0.7.6"

is this a vulnerability of this program?
btw I'm not running chainweb.

**Comment by larskuhtz** [comment]
This looks like a legitimate request for a chainweb node. I guess, someone/something injected your IP address into the p2p database of some chainweb node. Or your IP was used by a chainweb node before you got it. Nodes will try old IPs in their database from time to time before finally dropping them.

Let us know if you get many requests like this or if the number of requests increases even though you are not running chainweb nodes.
