### ISSUE TITLE
SQLite-based checkpointer for Pact

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/chainweb-node#118]
As Pact has distinct user tables and a structure that is already very amenable to versioned history, propose to implement checkpoints directly in SQLite as opposed to (a) copying SQLite DB files (b) using BTRFS or some filesystem solution (c) using RocksDB. 

### Why not RocksDB

RocksDB is suggested as inferior for Pact mainly because the need to have so many user schemas requiring extensive keyspace operations. Also, SQLite actually outperforms RocksDB for single-threaded indexed queries, see <https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks> at ~50us where Pact has seen db updates in the <20us zone.

As for SQLite size limitations, they are actually not small and will probably suffice for many years, see <https://www.sqlite.org/limits.html>. However this design proposes that multiple connections can be used, where connections own some count of user tables. This can be introduced later as long as there is design support for it now.

Note lastly that RocksDB snapshots are not persisted to disk so that solution is not usable.

Lastly, this design actually leverages SQLite's performant indexing to leverage relational SQL as the versioning mechanism, as opposed to previous SQLite Pact usage which looks more like a key-value store. Indeed the Pact language just wants a journaled key-value, but this solution will handle reorgs "relationally". 

## Overview

The main notion is of a **version** corresponding to a fork that will be used along with block height to determine the latest version of a key, and to label entries as "forked" (or simply delete them) when a reorg occurs.

#### Example user table use 

The following example will be used to illustrate the design. A user table will go through the following history. Row data will be represented with an arbitrary number. "Version" concept is detailed elsewhere but corresponds to a reorg history.

| key | block | version | data | notes |
|--|--|--|--|--|
| a | 10 | 1 | 123 | Version 1 represents current reorg/fork|
| b | 10 | 1 | 234 | |
| c | 11 | 1 | 456 | Reorg below replaces from here |
| a | 11 | 1 | 124 | | 
| d | 12 | 1 | 567 | |
| c | 12 | 1 | 457 | |
| c | 11 | 2 | 460 | Fork/reorg to Version 2 |
| b | 12 | 2 | 240 | |

Thus, a table scan at block 12 version 1 just before the reorg should return:

| key | block | version | data |
|--|--|--|--|
| a | 11 | 1 | 124 |
| b | 10 | 1 | 234 | 
| c | 12 | 1 | 457 | 
| d | 12 | 1 | 567 | 

A table scan at the end, post-reorg, should return:

| key | block | version | data |
|--|--|--|--|
| a | 10 | 1 | 123 |
| b | 12 | 2 | 240 | 
| c | 11 | 2 | 460 | 

#### Version detection

Block validation supplies a stream of `(block height [B],parent hash [P])` pairs. A **version** indicates the non-forked behavior of this stream, such that receiving a monotonically-increasing dense stream of block heights indicates a single version. 

When a block height arrives that is less than the expected next value, the version (V) will increment and version maintenance operations will occur. 

System will need to have a central version history table ordering all `(B,P)` pairs and associating a version. Re-orged pairs can be discarded. The "HEAD" version is maintained in memory and can be recovered from the version history table. 

The "block version" is the pair of (B,V) as seen in the examples above.

#### Table management

System will track all versioned system and user tables -- versioned system tables would include the Pact continuation table and refstore; user tables includes coin contract table. Tables should be associated with a database connection/file with some limit on how many tables should be in a file/conn. This initially can be a single connection but we want the design to support multiple connections. The central system tables can be in their own connection or share the first connection.

Tables will also be associated with the block version when they were created. Tables can optionally be dropped when reorged, or marked as old/invalid; table name in database can include the block version if desired. See "Deleting vs Marking" below.

#### Per-table versioning and history

Table operations will support reorgs by tracking versions directly in the relational schema. Queries will leverage indexes and "SELECT TOP 1" queries to find the latest key. 

Pact history requests will no longer need dedicated "transaction tables". 'txid' will be stored as a relational column. Note that Pact will no longer track multiple updates in a given txid for a key as this is (a) not a good practice and (b) not relevant to larger history. 

#### Deleting vs Marking on version changes

This solution supports either (a) _marking_ deactivated block versions by updating the version column with a `FORKED` code, or simply _deleting_ the row. Likewise, forked table creates can either associated the table as `FORKED` or simply drop the table. 

Deletion has the advantage of space compaction; marking can help with troubleshooting. While supporting both as a configuration option might be nice it will also slow development.

Decision: use deletion. Descriptions below will nonetheless use FORKED to indicate marking option. 

## Versioned table schema

All versioned tables will have the following schema:

Name | Type | Note | Index
|--|--|--|--|
| KEY | String | User key | Non-unique 
| BLOCK | Int | Block height | Non-unique 
| VERSION | Int | Reorg version |
| TXID | Int | Transaction ID for history | Non-unique
| DATA | JSON | User data | No index

Unique constraint is (KEY,BLOCK[,VERSION]). SQLite automatically adds ROWID which is actual primary key. TXID will have an index for history queries.

## Version maintenance

On a reorg, a new block version (B,V) will be introduced. 
1. Delete/mark all rows where BLOCK >= B . 
2. Drop/mark all tables that were created in BLOCK >= B. 

### On-demand version maintenance.

Version maintenance will be expensive, requiring operations on all versioned tables in the system. Version maintenance could however be on-demand. 

Tables could track when they were last maintained using (B,V). The first in-block operation to occur could test this to see what maintenance needs to be done. 

In the example above, consider if the updates/queries happened in block (15,2) instead of right at the reorg. Table would have (10,1) for block version, and see that (11,2) was a fork. Maintenance would occur then. 

Need to maintain fork history to apply all forks that might have occurred since table block version. 

Advantage of on-demand version maintenance is faster block processing assuming that not all tables are hit in every block.

Disadvantage is unpredictable work; maintaining all tables is possibly a more "even" workload.

DECISION: Attempt on-demand and fall back to "global" maintenance as time permits.

### Checkpoint begin with (B,H) supplied
- Detect version change; run maintenance on user tables as needed. (Note this could on-demand, see note above). 
- Compute block version (B,V) to put in environment for use in queries during this block.

### Checkpoint discard
- Might want to use SAVEPOINT in SQLite to discard. This would require more information in begin phase, or always use a SAVEPOINT and simply COMMIT on save.

### Checkpoint save
- Nothing required here, unless SAVEPOINT is used at which point commit.

### Single-key query for key K

select top 1 KEY,DATA where KEY = K [and VERSION != FORKED] order by BLOCK[, VERSION]

### Update key K to data D at block version (B,V) with txid T

- read row data D' for K as above
- write new row KEY = K, BLOCK = B, VERSION = V, TXID = T, DATA = (merge D' D)

### Select all valid keys (`keys` in Pact) 
Same query as single (without DATA) without `TOP 1`

### Row history queries
Simply query ordered by TXID [avoiding FORKED rows].

**Comment by marklnichols** [comment]
This seems like it will be so much better than a separate DB 'instance' for each fork (or each commit!).  
 > Tables will also be associated with the block version when they were created. 
I guess this implies that on a fork we would have to re-associate the tables to the block at the new fork point?

> When a block height arrives that is less than the expected next value, the version (V) will increment and version maintenance operations will occur.
I don't know what all the use cases are that lead to a new version, but will moving to a new 'version' be that simple?

I'll have to read it again, but at the moment I don't quite get what the 'version maintenance' does.

Seems like this requires some major Pact work? (Thanks Stuart!)

**Comment by slpopejoy** [comment]
> I guess this implies that on a fork we would have to re-associate the tables to the block at the new fork point?
No, in an old fork where a table was created, that table simply disappears (either by dropping it or labeling it as FORKED). If transaction that created the table is re-introduced, a new table (with the same name if deleted, or we version the table name if FORKED label is used), is created.

Once the table create survives forking then it's just a matter of deleting rows in a fork.

> I don't know what all the use cases are that lead to a new version

There's only one: a fork, ie a validate shows up for an older (B,H) pair, implying that blocks >B are discarded. A version just makes it clear that a fork happened. 

The incrementing version is only important if you're keeping FORKED rows as it makes it clear that "this row is not in any active version". When deleting rows, it doesn't really do anything except make the fork points clear in the history. Where version is useful is in on-demand version maintenance.

> will moving to a new 'version' be that simple?

Once a new version is detected at B, you simply need to delete all rows in all versioned tables whose block height is >= B, and drop any tables that were created at or after B. The only trick is to do "on-demand maintenance" so you're not constantly running noop DELETE sql calls on tables that weren't touched in the fork. The naive approach (always delete on all tables on version change) is really simple.

> Seems like this requires some major Pact work?

Not on Pact per se, but on an implementation of `PactDb` that could live in the Chainweb repo. https://github.com/kadena-io/pact/blob/6ee63200e763d6ee5efc4d510ae81f24dd659bfe/src/Pact/Types/Persistence.hs#L308

**Comment by slpopejoy** [comment]
To elaborate, here are strategies for every method in `PactDb`:
```haskell
data PactDb e = PactDb {
    -- | Read a domain value at key, throwing an exception if not found.
    _readRow :: forall k v . (IsString k,FromJSON v) =>
                Domain k v -> k -> Method e (Maybe v)
```
See "Single key query" above.
```haskell
    -- | Write a domain value at key. WriteType argument governs key behavior.
  , _writeRow :: forall k v . (AsString k,ToJSON v) =>
                 WriteType -> Domain k v -> k -> v -> Method e ()
```
See "Update key K to data D at block version (B,V) with txid T". T is transmitted to the backend in `beginTx` below.
```haskell
    -- | Retrieve all keys for user table.
  , _keys ::  TableName -> Method e [RowKey]
```
See "Select all valid keys" above.
```haskell
    -- | Retrieve all transaction ids greater than supplied txid for table.
  , _txids ::  TableName -> TxId -> Method e [TxId]
```
See "Row history queries" above.
```haskell
    -- | Create a user table.
  , _createUserTable ::  TableName -> ModuleName -> Method e ()
```
Table maintenance, will want to track (B,V) with table as well as what DB connection it is in. 
```haskell
    -- | Get module, keyset for user table.
  , _getUserTableInfo ::  TableName -> Method e ModuleName
```
Table metadata.
```haskell
    -- | Initiate transaction. If TxId not provided, commit fails/rolls back.
  , _beginTx :: Maybe TxId -> Method e ()
    -- | Commit transaction, if in tx. If not in tx, rollback and throw error.
    -- Return raw TxLogs, for use in checkpointing only (not for transmission to user).
  , _commitTx ::  Method e [TxLog Value]
    -- | Rollback database transaction.
  , _rollbackTx :: Method e ()
```
These translate directly to SQLite calls.
```haskell
    -- | Get transaction log for table. TxLogs are expected to be user-visible format.
  , _getTxLog :: forall k v . (IsString k,FromJSON v) =>
                 Domain k v -> TxId -> Method e [TxLog v]
}
```
This is simply a select where TXID=TxId.

**Comment by slpopejoy** [comment]
Same for `Checkpointer`. 

```haskell
data Checkpointer = Checkpointer
    { restore :: BlockHeight -> BlockHash -> IO (Either String PactDbState)
```
We are given (B<sub>restore</sub>,H<sub>parent</sub>). Our state is 
- a history of (B,H) pairs. (B,H)<sub>current</sub> is pair at the max B value.
- a history of (V,B) pairs. V<sub>current</sub> is the max V value.

Enforce invariant that the history has (B<sub>restore</sub>-1, H<sub>parent</sub>). 

Enforce that B<sub>restore</sub> is not greater than B<sub>current</sub>+1.

If B<sub>restore</sub> is B<sub>current</sub>+1, then this is normal sequential execution. 
1. Set environment to (V,B)<sub>env</sub> to (V<sub>current</sub>,B<sub>restore</sub>).
2. Start a SAVEPOINT.

If B<sub>restore</sub> is less than or equal to B<sub>current</sub>, then we are forking:

1. Set environment (V,B)<sub>env</sub> to (V<sub>current</sub> + 1,B<sub>restore</sub>).
2. Store (V,B)<sub>env</sub> in history.
3. Maintain version.
  a. Naive table maintenance only: for all versioned tables, delete all rows where B<sub>row</sub> >= B<sub>env</sub>.
  b. Naive table maintenance only: Drop all tables created at or after B<sub>env</sub>.
  c. Delete all (B,H) history at or after B<sub>env</sub>.
4. Start a SAVEPOINT.

```haskell
    , restoreInitial ::IO (Either String PactDbState)
```
There is no forking here. Establish initial values in history and set environment. SAVEPOINT is not needed.
```haskell
    , save :: BlockHeight -> BlockHash -> PactDbState -> IO (Either String ())
```
Given (B,H)<sub>save</sub>:
1. Commit SAVEPOINT. 
2. Store (B,H)<sub>save</sub> in history.
```haskell
    , saveInitial :: PactDbState -> IO (Either String ())
```
No action.
```haskell
    , discard :: PactDbState -> IO (Either String ())
    }
```
Rollback SAVEPOINT.

**Comment by slpopejoy** [comment]
## On-demand maintenance ##

Our state is a set of "touched" table names TOUCHED in the current block, a history (T,(V,B)) recording the last time a table was "touched", and (V,B) history as described above. (V,B)<sub>env</sub> is in the environment indicating current block height and version. 

A table is "touched" the first time in a block when any operation in `PactDb` refers to it. For table T, if it is in TOUCHED, then no-op. If it is not, add T to TOUCHED and continue.

Lookup (V,B)<sub>previous</sub> in history by T. If V<sub>env<sub> == V<sub>previous</sub>, no-op.

If V<sub>previous</sub> is less than V<sub>env</sub>, do maintenance:
1. compute B<sub>fork</sub> as the minimum B value in history where V is in [V<sub>previous</sub>..V<sub>env</sub>].
2. If table was created at or after B<sub>fork</sub>, drop the table. Obviously, most operations will fail after this, except create-table. 
3. If not dropping table, delete all rows where B<sub>row</sub> >= B<sub>fork</sub>.

**Comment by slpopejoy** [comment]
## Recovery

An important part of this solution will be supporting recovery, ie that we can start up Chainweb and resume from some point in history. 

This should actually be very easy with this design, as long as we ensure that all history is represented as an actual SQLite table and not an in-memory structure. 

However, we will undoubtedly need to signal back to Chainweb in the case where we are not up to the current blockheight for our chain, to have it play through payloads to get up-to-date. 

For this reason it is very important to do all database operations in a relevant transaction or SAVEPOINT, so that partial state does not get written in a crash scenario. Our various histories (B,H), (V,B) etc must all be "in-sync" with each other.

**Comment by slpopejoy** [comment]
## Multiple Connections and System Versioned State ##

To be future-proof against running out of space in a given SQLite file, we should have a tunable parameter for how many tables a connection should support. This can be quite high (e.g. 100, 1,000 etc). When a table is created it should check to see if the current connection can support it. We also could base this on row count, since some tables will be underused.

Clearly, this information (which connection a table is stored in) needs to be stored in a non-versioned system table itself.

Thus, we have some system state that is not versioned, like the table-to-connection lookup. We also have _versioned system tables_, where the data being stored are the RefStore, or the Pact continuation state, or the TxId. These should be actively maintained -- ie not on-demand -- but otherwise maintenance is identical to user tables. Their keys should represent the relevant keys in the state structure, thus RefStore is by module name etc, Pact state is by PactId. 

Note that `PactDb` already specifies some special tables for KeySets and for modules. 

The first connection should store genesis tables and all system tables. The user tables can maybe be in this, or go into a new connection where count is maintained.

**Comment by gregorycollins** [comment]
Hi all,

I don't think the version field is necessary anywhere, i.e. it can always be a proxy for blockheight. If you represent your tables so:

```sql
-- we need this for history walk and to confirm we are on the right chain 
CREATE TABLE BlockHistory (
    blockheight UNSIGNED BIGINT,
    hash BLOB,
    CONSTRAINT blockHashConstraint UNIQUE (blockheight, hash));

-- records creation blockheight for each user table
CREATE TABLE VersionedTableCreation(
    tablename TEXT NOT NULL,
    blockheight BIGINT NOT NULL,
    CONSTRAINT vt_creation_unique UNIQUE(tablename));

-- records last mutation blockheight for each user table
CREATE TABLE VersionedTableMutation(
    tablename TEXT NOT NULL,
    blockheight BIGINT NOT NULL,
   CONSTRAINT vt_mutation_unique UNIQUE(tablename, blockheight));
CREATE INDEX vt_mutation_bh ON VersionedTableMutation(blockheight);

-- an individual versioned table
CREATE TABLE versioned_foo(
    rowkey TEXT NOT NULL,
    blockheight UNSIGNED BIGINT NOT NULL,
    txid UNSIGNED BIGINT NOT NULL,
    tabledata BLOB,    -- here NULL tabledata has to be interpreted as "the rowkey was deleted at this block"
    CONSTRAINT versioned_foo_unique UNIQUE(rowkey, blockheight));
CREATE INDEX versioned_foo_bh ON versioned_foo(blockheight);
```

Implementing operations:

### lookup

Lookup is much the same as before (`ORDER BY blockheight DESC LIMIT 1`)

### insert

Insert touches the mutation and creation tables before writing the row as before:

```sql
INSERT OR IGNORE INTO VersonedTablesCreation VALUES (table, bh);
INSERT OR IGNORE INTO VersionedTablesMutation VALUES (table, bh);
```

### restore

Let's say we want to restore so that we can run a block having hash _b_, parent hash _p_, and block height _h_. To restore to the state as of the parent block:

  - We check the precondition of the blocks table as before to make sure we have `(p, h-1)` in `BlockHistory`.
  - Collect list of tables that need to be dropped:
```sql
SELECT DISTINCT tablename FROM VersionedTableCreation where blockheight >= h;
```
  - Drop those tables.
  - Collect list of user tables for vacuum:
```sql
SELECT DISTINCT tablename FROM VersionedTableMutation where blockheight >= h;
```
  - Vacuum each table:
```sql
DELETE FROM some_versioned_table WHERE blockheight >= h;
```

This series of actions should destroy any modification made to the db after block _h_-1 -- any row in a versioned table having blockheight >= _h_  should have a row in VersionedTableMutation corresponding to that block, and so the vacuum should sweep it up. Each individual table vacuum should take time proportional to the number of mutated rows, and we'll only consider dirty tables for vacuum. Stu, can I convince you that the DB should be safe for forward play of block _b_ transactions after we do this?
