### ISSUE TITLE
Propagation of ChainwebVersion 

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/chainweb-node#127]
The is issue serves two related purposes:

1. Derive the `ChainGraph` from the `ChainwebVersion`.
2. Propagate the `ChainwebVersion` reified as type parameter.

The `ChainwebVersion` and the `ChainGraph` are static values for a given chainweb instance. They are both represented as terms at runtime but are morally types. Therefore it makes sense to reify the `ChainwebVersion` value at the topmost layer, let the constraint solver propagate it, and inject it via reflection where it is used. By tagging data types that depend on the `ChainwebVersion` and in particular the `ChainGraph` with the reified `ChainwebVersion` we also get static consistency properties. For instance, we are guaranteed that the `ChainId`s of a `BlockHash` actually belong to the graph that is in scope.

Currently, we use `given` in a several places for the `ChainGraph`. This which has the benefit of not having to propagate the `ChainGraph` as explicit parameter to each use site, but instead have the constraint solver propagate it for us (which is convenient since dictionaries are propagate backward and forward through the control graph). Another major benefit is that it supports keeping code pure that otherwise would require some monadic context to provide the `ChainGraph` in the environment. That is, is for instance, convenient for defining type class instances for classes that don’t expect a parameter for a monadic environment. E.g. `class Given ChainGraph => Arbitrary chainId where …` instead of `class HasChainGraph m => Arbitrary (m ChainId) where …`.

**Comment by mercadoa** [comment]
➤ Lars Kuhtz commented:

This private gist ( https://gist.github.com/larskuhtz/94fbeb7f8fce86ec17411fc7e6f45d49 ) contains a prototype implementation that outlines the approach.

**Comment by chessai** [comment]
This is done.
