### ISSUE TITLE
add hardware requirements to the readme

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweb-node#1296]
FAQ:
https://discord.com/channels/502858632178958377/641021540393025651/908302070019399750

**Comment by dandv** [comment]
I can't access that Discord link, but I ran into this issue as well - #1305.

**Comment by trendzetter** [comment]
@dandv check the linked pr above; requirements are in the proposed change to readme
Join Kadena on discord: https://discord.com/invite/bsUcWmX
