### ISSUE TITLE
BlockHeader given with no associated Payload

### ISSUE THREAD

**Issue by maniconef** [kadena-io/chainweb-node#1297]
i have this error "No associated Payload" . Any help? Thanks!

021-11-12T14:56:25.41042913Z Error [Thread 5] failed to submit solved work: HttpExceptionRequest Request {
host = "xxxxxx"
port = 1848
secure = False
requestHeaders = []
path = "chainweb/0.0/mainnet01/mining/solved"
queryString = ""
method = "POST"
proxy = Nothing
rawBody = False
redirectCount = 10
responseTimeout = ResponseTimeoutDefault
requestVersion = HTTP/1.1
proxySecureMode = ProxySecureWithConnect
}
(StatusCodeException (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Fri, 12 Nov 2021 14:56:25 GMT"),("Server","Warp/3.3.17"),("X-Server-Timestamp","1636728985"),("X-Chainweb-Node-Version","2.11")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "No associated Payload")

**Comment by larskuhtz** [comment]
This can happen for various reasons:

* Most likely: the miner returns a solution for a header for which the node just received another solution. In this case the job, including the payload, is removed on the server side.

* also possible: the miner already submitted the solution before and the solution got accepted by the server, but an network/http error occurred while receiving the response. If the client retries it would get this message.

* Other possible reasons: the mining api of chainweb-node is served via a load balancer and the client submits the work from a different node than the one from which it originally got the work.

If this happens only occasionally, it is not reason for concern.

**Comment by edmundnoble** [comment]
Closing for lack of response.
