### ISSUE TITLE
What value should be used for license in module headers?

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/chainweb-node#130]
Assuming, that there is no license, should we use `None`? In that case, should the License file be deleted?

**Comment by mercadoa** [comment]
➤ Colin Woodbury commented:

Has anyone talked about licensing for Chainweb yet?

**Comment by mercadoa** [comment]
➤ Doug Beardsley commented:

My vote is AllRightsReserved.  None is not recognized by Cabal 2.0 and it doesn't work with Nix either.  See for example:

$ nix-build
warning: unknown setting 'signed-binary-caches'
warning: dumping very large path (> 256 MiB); this may run out of memory
building '/nix/store/f9vc1isa9fbqi918fc6gy9vrc31d1y7r-cabal2nix-kadena.drv'...
installing
cabal2nix: Distribution.Nixpkgs.Haskell.FromCabal.License.fromCabalLicense: unknown licenseUnknownLicense "None"
Choose one of: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT, ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense
CallStack (from HasCallStack):
  error, called at src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs:38:62 in cabal2nix-2.5-JLIXgX7xI6CFvjg2o3boSt:Distribution.Nixpkgs.Haskell.FromCabal.License
builder for '/nix/store/f9vc1isa9fbqi918fc6gy9vrc31d1y7r-cabal2nix-kadena.drv' failed with exit code 1When I do this on private projects I usually put something like the following in the LICENSE file:

Copyright (c) 2018, Kadena LLC
All rights reserved.This gives us maximum possible flexibility.  We can always release it under a more permissive open source license later.

**Comment by chessai** [comment]
Closing in favour of #136.
