### ISSUE TITLE
Where are the hardware specs to run a node?

### ISSUE THREAD

**Issue by dandv** [kadena-io/chainweb-node#1305]
https://docs.kadena.io/contribute-to-the-network/run-a-node and https://kadena-io.github.io/kadena-docs/Public-Chain-Docs.html#run-a-node (see https://github.com/kadena-io/kadena-docs/issues/7) both point to

> "[Hardware specs required to run a node](https://github.com/kadena-io/chainweb-node): Kadena official README".

That link points to this repo README, but the README doesn't mention any hardware specs.

**Comment by trendzetter** [comment]
https://github.com/kadena-io/chainweb-node#installing-chainweb
it's merged in the readme

**Comment by larskuhtz** [comment]
solved by #1295
