### ISSUE TITLE
Querying account balance 

### ISSUE THREAD

**Issue by oliverw** [kadena-io/chainweb-node#1352]
Is there an example on how to query one's account balance using the API?

I have tried the Rosetta API but all my attempts failed various HTTP status codes because you need to specify so many parameters due to the general purpose design of the Rosetta API.

**Comment by mightybyte** [comment]
Check out how https://balance.chainweb.com/ does it.  Using the network inspector in your browser is easiest but code is here https://github.com/kadena-community/kadena-balance.
