### ISSUE TITLE
Investigate custom "Ingress" and "Egress"

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/chainweb-node#142]
Currently, EC2 instance HTTP traffic ingress/egress is left "wide open". If you knew the IP addresses of any of our nodes, you could connect random Chainweb instances to our network.

At least for Testnet, we'd like to have control over who is in our network. Approaches:

1. [Terraform] Better define ingress/egress fields in our Security Group definitions?
2. [Terraform] Actually define a non-default AWS internal VPS? 
3. [Haskell] Support special lists of IP address that can be read at runtime, indicating special HTTP traffic to allow?

My personal vote is for (1).

**Comment by mercadoa** [comment]
➤ anagha@kadena.io commented:

Talk to Doug about VPN aspects

**Comment by fosskers** [comment]
VPS, not VPN.

**Comment by mercadoa** [comment]
➤ Doug Beardsley commented:

We're putting this on hold for now, thinking we may skip the semi-private phase.

**Comment by mercadoa** [comment]
➤ anagha@kadena.io commented:

Moved from v1 to v2
