### ISSUE TITLE
cabal build Failed

### ISSUE THREAD

**Issue by Nixiangyu** [kadena-io/chainweb-node#1468]
HEAD is now at 5bfe043 Edmund/rocksdb delete range (#12)
HEAD is now at 10f21e9 Merge pull request #5 from kadena-io/ghc-9
HEAD is now at 3081be05 walk back 4.2.1 (#1000)
HEAD is now at 6c8dd2e Fix hashable version incompatibility
HEAD is now at 0542786 fix for template-haskell-2.16
HEAD is now at d8019c3 use Type instead of *
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - chainweb-storage-0.1.0.0 (lib) (requires build)
 - pact-4.3.1 (lib) (requires build)
 - chainweb-2.15 (lib:chainweb, exe:chainweb-node, exe:cwtool, test:chainweb-tests, bench:bench) (first run)
Starting     chainweb-storage-0.1.0.0 (lib)
Starting     pact-4.3.1 (lib)
Building     chainweb-storage-0.1.0.0 (lib)
Building     pact-4.3.1 (lib)
Installing   pact-4.3.1 (lib)
Completed    pact-4.3.1 (lib)

Failed to build chainweb-storage-0.1.0.0.
Build log (
/Users/nancy/.cabal/logs/ghc-8.10.7/chnwb-strg-0.1.0.0-862d5191.log ):
Configuring library for chainweb-storage-0.1.0.0..
Preprocessing library for chainweb-storage-0.1.0.0..
Building library for chainweb-storage-0.1.0.0..
[1 of 5] Compiling Data.CAS         ( src/Data/CAS.hs, dist/build/Data/CAS.o, dist/build/Data/CAS.dyn_o )
[2 of 5] Compiling Data.CAS.Forgetful ( src/Data/CAS/Forgetful.hs, dist/build/Data/CAS/Forgetful.o, dist/build/Data/CAS/Forgetful.dyn_o )
[3 of 5] Compiling Data.CAS.HashMap ( src/Data/CAS/HashMap.hs, dist/build/Data/CAS/HashMap.o, dist/build/Data/CAS/HashMap.dyn_o )
[4 of 5] Compiling Data.CAS.RocksDB ( src/Data/CAS/RocksDB.hs, dist/build/Data/CAS/RocksDB.o, dist/build/Data/CAS/RocksDB.dyn_o )
<command line>: dlopen(/Users/nancy/.cabal/store/ghc-8.10.7/lib/libHSrcksdb-hskll-1.0.1-96ae8c10-ghc8.10.7.dylib, 0x0005): symbol not found in flat namespace '_rocksdb_filterpolicy_create'
cabal: Failed to build chainweb-storage-0.1.0.0 (which is required by
chainweb-2.15). See the build log above for details.

**Comment by edmundnoble** [comment]
Hi @Nixiangyu, please provide some more details about the system you're building on and let me know if this is still an issue. Thank you.

**Comment by chessai** [comment]
@Nixiangyu Can you provide the following specific points of information:

- What operating system/version are you running (appears to be MacOS; if so, which version?)
- What commit/tag of chainweb-node are you running? You appear to be using 2.15 (consistent with the time you reported this issue)
- Are you just running `cabal build`?

It's possible something went wrong with your rocksdb installation.

Could you also try following the instructions in the [README](https://github.com/kadena-io/chainweb-node/blob/master/README.md) for the latest version (2.19.1) and see if that works for you?
