### ISSUE TITLE
Rework logging

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/chainweb-node#151]
Lars has mentioned that our logging infrastructure is split among many places. Perhaps `yet-another-logger` needs some love, so that we can pull custom logging code out of Chainweb.

**Comment by mercadoa** [comment]
➤ lars commented:

I think we may create a new log-message package that would be independent of yet-another-logger, but could be used with it.

**Comment by chessai** [comment]
This issue is too vague and unactionable, mostly due to the passage of time. Closing.
