### ISSUE TITLE
docker compose --profile initialize-db up -d chainweb-initialize-db not working any more

### ISSUE THREAD

**Issue by toco3DevTobias** [kadena-io/chainweb-node#1523]
Using docker compose to install webchain-node the following error occurs when enter the command:
**docker compose --profile initialize-db up -d chainweb-initialize-db**

chainweb-node: Data.CAS.RocksDB.checked: error while Data.CAS.RocksDB.get: Corruption: Unknown Footer version. Maybe this file was created with newer version of RocksDB?

The step before 
**docker compose --profile initialize-db up -d chainweb-initialize-db-sync**
still works and exit with code 0. 

This happens since repository pulled the latest version of chainweb-node.

**Comment by xiownthispla** [comment]
This was happening to me as well yesterday (2.15) on a fresh ubuntu install and today same thing with 2.16.
[+] Running 3/3
 ⠿ Container chainweb-initialize-db-config  Created                                                                                                                                                   0.1s
 ⠿ Container chainweb-initialize-db-sync    Created                                                                                                                                                   0.0s
 ⠿ Container chainweb-initialize-db         Created                                                                                                                                                   0.1s
Attaching to chainweb-initialize-db
chainweb-initialize-db  | WARNINGS:
chainweb-initialize-db  | warning: The node is configured to listen only on a private network. Please use a public network as interface configuration, e.g. '*' or '0.0.0.0'
chainweb-initialize-db  | warning: Default bootstrap nodes are ignored and no known peers are configured. This node won't be able to communicate with the network.
chainweb-initialize-db  | warning: This node is configured to communicate only with the default bootstrap nodes.
chainweb-initialize-db  | 2022-08-29T16:17:49.352Z [Info] [chainwebVersion=mainnet01|type=ChainwebApp] start ServiceDate
chainweb-initialize-db  | 2022-08-29T16:17:49.352Z [Warn] [chainwebVersion=mainnet01|type=ChainwebApp] This version of chainweb node will stop to work at 2022-12-01 00:00:00 UTC. Please upgrade to a new version before that date.
chainweb-initialize-db  | 2022-08-29T16:17:50.173Z [Info] [chainwebVersion=mainnet01|type=ChainwebApp] opened rocksdb in directory "/chainweb/db/0/rocksDb"
chainweb-initialize-db  | 2022-08-29T16:17:50.173Z [Info] [chainwebVersion=mainnet01|type=ChainwebApp] backup config: BackupConfig {_configBackupApi = EnableConfig {_enableConfigEnabled = False, _enableConfigConfig = BackupApiConfig}, _configBackupDirectory = Nothing}
chainweb-initialize-db  | 2022-08-29T16:17:50.189Z [Warn] [chainwebVersion=mainnet01|type=ChainwebApp] Unable verify configured host 0.0.0.0: No peers are available.
chainweb-initialize-db  | 2022-08-29T16:17:51.047Z [Info] [chainwebVersion=mainnet01|type=ChainwebApp] Local Peer Info: {"id":"id","address":{"hostname":"0.0.0.0","port":4445}}
chainweb-initialize-db  | 2022-08-29T16:17:51.047Z [Info] [chainwebVersion=mainnet01|peerId=4siZDF|port=4445|host=0.0.0.0|type=ChainwebApp] 0 out of 0 peers are reachable
chainweb-initialize-db  | 2022-08-29T16:17:51.097Z [Info] [chainwebVersion=mainnet01|peerId=4siZDF|port=4445|host=0.0.0.0|component=init|type=ChainwebApp] start pruning databases
chainweb-initialize-db  | 2022-08-29T16:17:51.141Z [Info] [chainwebVersion=mainnet01|type=ChainwebApp] ServiceDate stopped
chainweb-initialize-db  | chainweb-node: Data.CAS.RocksDB.checked: error while Data.CAS.RocksDB.get: Corruption: Unknown Footer version. Maybe this file was created with newer version of RocksDB?
chainweb-initialize-db  | CallStack (from HasCallStack):
chainweb-initialize-db  |   error, called at src/Data/CAS/RocksDB.hs:806:9 in chainweb-storage-0.1.0.0-f3a9a0fb87e1db9e6e884c163c32602d46a03c653f541de21964800a7ef48940:Data.CAS.RocksDB
chainweb-initialize-db  |   checked, called at src/Data/CAS/RocksDB.hs:884:20 in chainweb-storage-0.1.0.0-f3a9a0fb87e1db9e6e884c163c32602d46a03c653f541de21964800a7ef48940:Data.CAS.RocksDB
chainweb-initialize-db exited with code 1

**Comment by DevopsGoth** [comment]
Those S3 backups need to be replaced.  Please stand by while the backups are repaired; this issue will be closed when that is complete.

**Comment by toco3DevTobias** [comment]
Any news - progress of this?
