### ISSUE TITLE
The log needs to support the logrotate mechanism.

### ISSUE THREAD

**Issue by JonathanHenderson** [kadena-io/chainweb-node#1535]
Currently, the log does not support the logrotate mechanism, resulting in smaller and smaller disk space.

root@root:/opt/kda/logs# ls -lthr
-rw-r----- 1 root root 4.3G 9月  20 07:55 kda.log

**Comment by trendzetter** [comment]
Run as a systemd service to syslog and let syslog rotate it? Thats how it seems to work for me

**Comment by JonathanHenderson** [comment]
I've tried doing this before, but it didn't work.
chainweb-node always writes data in the same file, and does not write data in an appending manner.

-rw-r--r-- 1 root root 2.1G Sep 10 00:00 kda.log-20220910
-rw-r--r-- 1 root root 2.4G Sep 11 00:00 kda.log-20220911
-rw-r--r-- 1 root root 2.6G Sep 12 00:00 kda.log-20220912
-rw-r--r-- 1 root root 2.8G Sep 13 00:00 kda.log-20220913
-rw-r--r-- 1 root root 3.0G Sep 14 00:00 kda.log-20220914
-rw-r--r-- 1 root root 3.2G Sep 15 00:00 kda.log-20220915
-rw-r--r-- 1 root root 3.5G Sep 16 00:00 kda.log-20220916
-rw-r--r-- 1 root root 3.7G Sep 17 00:00 kda.log-20220917
-rw-r--r-- 1 root root 3.9G Sep 18 00:00 kda.log-20220918
-rw-r--r-- 1 root root 4.1G Sep 19 00:00 kda.log-20220919
-rw-r--r-- 1 root root 4.3G Sep 20 00:00 kda.log-20220920
-rw-r--r-- 1 root root 4.5G Sep 21 00:00 kda.log-20220921
-rw-r--r-- 1 root root 4.5G Sep 21 02:48 kda.log

**Comment by JonathanHenderson** [comment]
Can you provide a way to reopen the log file? Just like Nginx does.

**Comment by trendzetter** [comment]
> I've tried doing this before, but it didn't work. chainweb-node always writes data in the same file, and does not write data in an appending manner.

It might be related to how you are starting it.  I don't see this problem when running it as a systemd service. Could you specify how you run chainweb-node so to see how to reproduce the behavior.

**Comment by JonathanHenderson** [comment]
2022-09-29T10:31:49.200Z [Error] [chainwebVersion=mainnet01|peerId=NNuC6w|port=8443|host=8.209.242.76|type=ChainwebApp] Only 5 out of 12 bootstrap peers are reachable.Required number of reachable bootstrap nodes: 6
2022-09-29T10:31:49.249Z [Info] [chainwebVersion=mainnet01|type=ChainwebApp] ServiceDate stopped

What should I do?

**Comment by JonathanHenderson** [comment]
The program cannot be started, and retrying multiple times does not work.
