### ISSUE TITLE
Add nix-build to CI for chainweb-node

### ISSUE THREAD

**Issue by jwiegley** [kadena-io/chainweb-node#1539]
Since updates in dependencies have a chance of breaking the Nix build, it would be nice to at least know when this has happened by adding a non-required CI job to chainweb-node, so that those in the company who support our Nix support can be notified and submit a fix.

**Comment by chessai** [comment]
Looks like this will be resolved by #1565.

**Comment by chessai** [comment]
Resolved by https://github.com/kadena-io/chainweb-node/commit/4443f711256e575b008896c49b42626cde2e1463
