### ISSUE TITLE
The program won't start, what should I do?

### ISSUE THREAD

**Issue by JonathanHenderson** [kadena-io/chainweb-node#1541]
2022-09-29T10:19:12.655Z [Error] [chainwebVersion=mainnet01|peerId=_0oGnM|port=1789|host=8.209.242.76|type=ChainwebApp] Only 5 out of 12 bootstrap peers are reachable.Required number of reachable bootstrap nodes: 6

**Comment by JonathanHenderson** [comment]
databaseDirectory: null
resetChainDatabases: false
chainweb:
  allowReadsInLocal: false
  rosetta: false
  onlySyncPact: false
  throttling:
    local: 0.1
    mining: 5
    global: 200.0
    putPeer: 21
  serviceApi:
    payloadBatchLimit: 1000
    interface: '*'
    port: 1848
  validateHashesOnReplay: false
  backup:
    api:
      enabled: false
      configuration: {}
    directory: null
  chainwebVersion: mainnet01
  pactQueueSize: 2000
  mining:
    coordination:
      enabled: false
      updateStreamTimeout: 240
      limit: 1200
      updateStreamLimit: 2000
      miners: []
    nodeMining:
      miner:
        account: ''
        predicate: keys-all
        public-keys: []
      enabled: false
  minGasPrice: 1.0e-8
  p2p:
    peer:
      certificateChainFile: null
      key: null
      interface: '*'
      certificateChain: null
      hostaddress:
        hostname: 0.0.0.0
        port: 1789
      keyFile: null
    maxPeerCount: 50
    private: false
    ignoreBootstrapNodes: false
    maxSessionCount: 10
    bootstrapReachability: 0.5
    sessionTimeout: 240
    peers: []
  gasLimitOfBlock: 150000
  reorgLimit: 480
  headerStream: false
  mempoolP2p:
    enabled: true
    configuration:
      pollInterval: 30
      maxSessionCount: 6
      sessionTimeout: 300
  reintroTxs: true
  cuts:
    pruneChainDatabase: none
    fetchTimeout: 3000000
    initialBlockHeightLimit: null
logging:
  telemetryBackend:
    enabled: true
    configuration:
      handle: stdout
      color: auto
      format: text
  backend:
    handle: stdout
    color: auto
    format: text
  logger:
    log_level: info
    queue_size: 1000
    exception_wait: 1000
    exit_timeout: 1000000
    scope: []
    exception_limit: 10
    policy: discard
  clusterId: null
  filter:
    default-rate: 1
    rules: []
    default: debug

**Comment by JonathanHenderson** [comment]
nohup /opt/kda/chainweb-node --config-file=/opt/kda/config.yaml --database-directory /opt/kda/data/ --log-handle file:/opt/kda/logs/kda.log  2>&1 &

**Comment by JonathanHenderson** [comment]
./chainweb-node --print-config > config.yaml
I created the config file and started the program with the above command, but the program won't start, I tried several times to no avail.

**Comment by larskuhtz** [comment]
There were not enough bootstrap nodes available. This is now fixed and your node should start.

For the future: you can lower the threshold for the number of available bootstrap nodes at startup using the respective configuration option.
