### ISSUE TITLE
GNU/Linux Debian 11 - 5.19.0-0.deb11.2-amd64 - build error - cabal: Error parsing project freeze file

### ISSUE THREAD

**Issue by blackmennewstyle** [kadena-io/chainweb-node#1586]
I'm trying to build `chainweb-node v2.17.1` and i'm getting the floowing error:
```
cabal build
cabal: Error parsing project freeze file
/home/ceedii/chainweb-node-2.17.1/cabal.project.freeze:362:
Parse of field 'index-state' failed (index-state must be a unix-timestamps
(e.g. '@1474732068'), a ISO8601 UTC timestamp (e.g. '2016-09-24T17:47:48Z'),
or 'HEAD'): hackage.haskell.org 2022-12-03T04:30:51Z

```

**Comment by edmundnoble** [comment]
What's `cabal --version` show you?

**Comment by blackmennewstyle** [comment]
I'm using:
```
cabal-install version 3.0.0.0
compiled using version 3.0.1.0 of the Cabal library
```

**Comment by edmundnoble** [comment]
It seems that the freeze files produced by `cabal freeze` as of 3.4 are not backwards compatible. I recommend installing a version of cabal greater than 3.4. Try https://www.haskell.org/ghcup/. I'll see about updating our docs.

**Comment by blackmennewstyle** [comment]
OK. Thanks for your answer, i will try to upgrade to a more recent version of cabal.
