### ISSUE TITLE
Incorrect Whitepaper link in "About" Section

### ISSUE THREAD

**Issue by LindaOrtega** [kadena-io/chainweb-node#1590]
The "About" section of this directory links to the Whitepapers, but when I click on the link there (https://docs.kadena.io/basics/whitepapers/overview), I get a "Page Not Found" error.

The new link to the Whitepapers should be: https://docs.kadena.io/kadena-docs/whitepapers/overview

**Comment by LindaOrtega** [comment]
Closing issue due to:
https://github.com/kadena-io/chainweb-node/pull/1592#issuecomment-1379532701
(broken link is now working)

**Comment by trendzetter** [comment]
this should probably be reverted since the migration to the other docs application has been reverted as well
