### ISSUE TITLE
Discussion: What conditions justify stopping a node?

### ISSUE THREAD

**Issue by fosskers** [kadena-io/chainweb-node#164]
Putting this here for posterity. For instance, under what conditions should mining be halted indefinitely? Are there validation failure scenarios that can't be recovered from? Etc. Please discuss.

**Comment by larskuhtz** [comment]
If serious unexpected failures occur we usually emit an `Error` log. In most cases those are emitted by `runForever` that is used to wrapper sub-components. `runForever` will restart the respective component.

Users are expected to monitor their logs for `Error` and take actions as needed. It would be nice to give users some tools to automate this. For instance

* Add configuration option / command-line flag ala `--stop-on-error`, which could be implemented as a logging backend, that would halt the node if an error is encountered.

* Configure `runForever` with a absolute or rate-limits for errors and halt the node (i.e. escalate the exception) if the limit is reached.
