### ISSUE TITLE
How to obtain the ubuntu binary?

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweb-node#1654]
It seems its missing for the 2.19 release assets:
https://github.com/kadena-io/chainweb-node/releases/tag/2.19

**Comment by lbpage** [comment]
@trendzetter per the release notes you can get the batteries included image here:

```
docker pull kadena/chainweb-node:2.19
```

and the ubuntu image here:

```
docker pull ghcr.io/kadena-io/chainweb-node/ubuntu:2.19
```

Let me know if you have any more issues.

**Comment by trendzetter** [comment]
I'm not using docker. there used to be a zipped download with just the chainweb executable for the previous releases.

**Comment by larskuhtz** [comment]
Those binaries are still there. You may scroll to the bottom of the release (https://github.com/kadena-io/chainweb-node/releases/tag/2.19). There is a list of assets which includes the binary archives.

Btw. those are the same binaries that are included in the docker images.

**Comment by trendzetter** [comment]
I see the assets I need were added 3 hours after the release, thanks for that!

I was already briefly looking into extracting the docker images but I thought this probably wasn't intended and lacking instruction.
