### ISSUE TITLE
chainweb-node crashes from time to time

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweb-node#1684]
It seems to crash after days sometimes weeks. I heard simular issues from other node operators.
Even when running with default settings on well spec machines. I think the settings are mostly default.
This is one of the messages I see when the vm shuts down (I am reproducing it from my human memory, not copy paste):
```
CPU#3 stuck for 25s! [chainweb-node:5368]
CPU#2 stuck for 30s! [chainweb-node:5368]
```

What is the recommended action for determining the issue and providing more information? I was thinking about tuning the loglevels but not sure where to start.

**Comment by chessai** [comment]
Hi @trendzetter, the following information would be helpful:

- What operating system/version are you running the node on?
- What are the specs of the system?
- Can you paste what settings you're running your node with?
- Can you paste more of the logs?
- Do you have any system monitoring that would show a steady growth in memory/cpu consumption?

**Comment by trendzetter** [comment]
I'll open a new issue for my new setup because I move to a different installation producing different crash messages.
