### ISSUE TITLE
Lars Preliminary Backlog

### ISSUE THREAD

**Issue by larskuhtz** [kadena-io/chainweb-node#185]
# Database backend

* [x] Detect consensus db schema changes
* [x] Command line flag to reset consensus db
* [x] Documentation for rocks db layer
* [x] More efficient TreeDB branches implementation (via reverse iterator) 
    Note that reverse that rocksdb reverse iteration isn't as performant as forward iteration.
    So, we should also consider chaining the order, assuming that we iterate backward 
    most of the time.
* [x] RocksDb API and in-memory Rocksdb implementation (either existing or based on hash map)
* [x] Use RocksDb column families to implement tables? However, check rocks db documentation about use cases for column families and different dbs. Column families may not be the best fit for us, or at least provide little benefits.
* [x] Atomic writes across Rocksdb tables
* [x] fork RocksDB package and add support for prefix seek.
* [x] database repair flag
* [x] Add Table API
* [x] use LZ4 compression for rocks db
* [x] efficient membership queries

# ChainDbs

* [x] Atomic writes for payload data (that lives in different cas). We may have to change the type of Payload db, so that the rocks db table is exposed from the type parameter.
* [x] Cut persistence
* [x] flag to re-evaluate chain db by (initializing cutdb with genesis cut and possibly injecting adding local cuts before accepting new cuts)
* [x] wrapper for payload db that adds tx-hash index (not a CAS, needs updates when tx are reintroduced)
* [x] Move optimizations in `limitCut` into `TreeDB`.
* [x] Add `NFData` constraint to all `TreeDB` functions that return a stream (to prevent leaking access to the backend from the bracket).
* [x] consider if payload db should be moved out of consensus, so that it can be sharded
  (Probably not a good idea)
* [x] option to check / rebuild secondary payload index `(payloadHash -> blockHeight)` for recent blocks. (e.g. in case it gets corrupted during a crash).
* [x] low-priority background check for secondary payload index

# Validation

* [x] Forward/Iterative block-chain validation for existing db (cf. cut persistence)
* [x] Include epoch start into block header and validate target value
* [x] Comprehensively document validation

# Cut Processing

* [x] Sample network consensus for estimating if and how much the local node is out of sync
    * [x] [optional/optimization] Short POW certificates to allow a node to prove that a fork received the claimed amount of work without further validation

# REST API

* [x] Suppress origin and suppress advertising peer (`--invisible` flag)
* [x] Sync payloads for “invisible nodes” (attach new block header and payload to cuthashes)
* [x] Binary encoding for cut hashes on the wire
* [x] Support content-type header (json and octet) for block-header and cut hashes

* [x] connection manager (`withConnectionManasger`) that uses openssl as backend for https connections.
* [x] client authentication

# Logging / Telemetry

* [x] Better mempool telemetry
* [x] Fix file handle logging
* [x] suppress pact info logs during replay
* [x] Roll Elasticsearch indices daily
* [ ] Per component log configuration (log-level and possibly backends)
* [ ] Add a logger field to all handles, instead of passing the logger separately.
* [x] move cut logs from base-backend to telemetry and make them more compact
* [x] support random sampling of logs (on a per log level base + possibly per log message level)

# Code cleanup

* [x] break cycles in rejoin spite *.Types modules
* [x] Read only versions of chain db handles
* [x] Hide constructor fields for BlockHeader
* [x] Hide constructor fields for payload data

# Misc

* [x] Option to run node (bootstrap node) without Mempool
* [x] function to sample network consensus (estimate consensus state without validation)
* [x] #1568

# P2P

* [x] P2P db api for reputation management
* [x] Increase default size of P2P db and use random sampling for P2P db sync (sync only subset)
* [x] add more jitter to peer selection
* [x] document relation between peer propagation and peer authentication
* [x] increase cost of peer creation (use pow?)

**Comment by enobayram** [comment]
This is a great list, we should probably go over these, spot the ones that are still relevant and turn them into tickets so that they can be tracked independently.

**Comment by larskuhtz** [comment]
Phew, good to see that quite a few of these go actually resolved over the past years :-)

**Comment by edmundnoble** [comment]
Checking things off as other issues are created for them.
