### ISSUE TITLE
Mining interrupted

### ISSUE THREAD

**Issue by z1617** [kadena-io/chainweb-node#1929]
`findWork: stalled for 6s. all chains with primed work may be stalled.` 

This type of errors happen very often, when node log such errors, the mining client couldn't get mining work,
which is unexpected.

**Comment by emilypi** [comment]
Thanks for the report @z1617 - we're looking into it today

**Comment by edmundnoble** [comment]
We should have a fix for this for the next point release, which is slated for this week or next week.

**Comment by edmundnoble** [comment]
Can you verify that this has been fixed by the 2.24.1 release, @z1617?

**Comment by z1617** [comment]
Thank you for addressing this issue @edmundnoble!

I will test it as soon as possible and provide feedback if I encounter any problems.
