### ISSUE TITLE
Log request bodies for send, local, poll, and listen

### ISSUE THREAD

**Issue by mightybyte** [kadena-io/chainweb-node#402]
This will be important for forensics when we go public soon.  There are a few different approaches we can take.  Let's discuss...

**Comment by larskuhtz** [comment]
Doing it within business logic via logging, possibly to a new telemetry backend, may be the best option here. This would be easier to implement than integrating it with low level generic HTTP request logging. 


*More detailed explanation:*

We already have detailed logging for all HTTP requests and responses, but we don't want to log request and/or repose bodies for *all* HTTP requests. One reason is that by default warp/wai streams bodies and logging them means to break the stream and buffer all of it in memory. Often that's fine, but not always. So, we would have to implement some way to configure for which URLs we want detailed logging and for which we don't want it. One way to do this would be to configure a prefix pattern for URLs. However, if the set of requests for which we want detailed body logs is fix, it is easier to do the logging on higher abstraction levels in the code.
