### ISSUE TITLE
No Default Miner

### ISSUE THREAD

**Issue by fosskers** [kadena-io/chainweb-node#427]
Currently, a `chainweb-node` will have its in-process miner defaulted to an unusable:
```haskell
noMiner :: Miner
noMiner = Miner (MinerId "NoMiner") (MinerKeys $ KeySet [] (Name "<" def))
```
Mining will still occur and rewards will be given, but without a keyset, there's no access to the coins.

In general, we shouldn't default to *any* default Miner. This should always be explicitly required from the user.

**Comment by gregorycollins** [comment]
N.B. I think we have a deficiency right now -- if there's no miner, nobody calls `mempoolNewBlock`, which means mempool never gets updated. I see two obvious fixes:

  - force mempool off when we're not going to run miner or mining coordinator
  - if mining is off, call `mempoolNewBlock` just for the side effects (or split the side-effecting functions out and call those directly) when the cut changes
