### ISSUE TITLE
Chainweb-node installing on ubuntu-18.04

### ISSUE THREAD

**Issue by swang133** [kadena-io/chainweb-node#467]
Hi there. 

I am using ubuntu-18.04. By just following " Installing Chainweb -> Instructions for Linux Users", terminal showed "chainweb-node: command not found". Is there any details related to installiation missing ?

Thank you.

Suyang

**Comment by crypt0biwan** [comment]
Try `./chainweb-node` ;-)

**Comment by olalawal** [comment]
I have the same issue getting core dumped when I run ./chainweb-node

**Comment by chessai** [comment]
Closing. Feel free to re-open if this is still an issue.
