### ISSUE TITLE
1.0.1 build failing

### ISSUE THREAD

**Issue by tbenst** [kadena-io/chainweb-node#637]
I'm on latest NixOS unstable:
```
> git checkout 1.0.1
> nix-build
[...]
52 out of 421 tests failed (215.07s)
Test suite chainweb-tests: FAIL
```

[full output](https://gist.github.com/tbenst/7000d1be67e9998e5fff452566fb403a)

**Comment by tbenst** [comment]
The current derivation is not compatible with sandboxing. building with `sudo nix-build --option sandbox false` succeeds. Might I suggest adding this instruction for NixOS users?

**Comment by emilypi** [comment]
@tbenst thanks for the issue. Yes, we should add this as part of the instructinos for NixOS users - this is a consequence of Nix sandboxing build tests. Some of the chainweb tests make use of the network, which breaks purity, causing Nix to fail. We're working on factoring out those tests in future builds.

**Comment by Fresheyeball** [comment]
@emilypi can we add `dontCheck` to the nix expression? If tests are not pure, then the expression should not run them.

**Comment by mightybyte** [comment]
This is fixed now.
