### ISSUE TITLE
Kadena discord requires poor security hygiene 

### ISSUE THREAD

**Issue by Fresheyeball** [kadena-io/chainweb-node#649]
For security reasons, its bad practice to give out ones carrier phone number. Because of this I (like many security invested people) use google voice, and forward to my carrier number. 

Right now the Kadena discord requires a non-voip phone number to message. 

![signal-attachment-2019-11-04-122100](https://user-images.githubusercontent.com/609279/68151408-e0e89d00-fefe-11e9-920f-30b0abc6ba5d.jpeg)

Since this discord is requiring that I give out my carrier number (IE greatly diminish my security hygiene), I cannot use it. Furthermore I would suggest that this is not a good practice, as anyone who wants to use this discord is giving away their carrier phone number and opening themselves up to social engineering attacks. 

For reference here is one such horror story about why this is a bad idea:
https://www.nytimes.com/2019/08/15/technology/personaltech/i-shared-my-phone-number-i-learned-i-shouldnt-have.html

**Comment by mightybyte** [comment]
This has been changed for awhile now.  Closing.
