### ISSUE TITLE
Installing the binary

### ISSUE THREAD

**Issue by pilipjan** [kadena-io/chainweb-node#657]
Hi im new with this. I finish installing the apt-base part but i dont know how to install the binary thing. Im using the google cloud

**Comment by emilypi** [comment]
Hi @pilipjan - you don't install the binary. You can simply put it in your `/usr/local/bin` or in any other directory of your choosing as long as you have access to it, and make it available as part of your PATH. There are many tutorials for how to do this out there, so I am closing this issue as it has less to do with Chainweb and more to do with Linux. Feel free to ask questions like this in the Discord so you can get some more informative step-by-step instructions.
