### ISSUE TITLE
Broken source nix-build with Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by Karasur** [kadena-io/chainweb-node#669]
52 out of 421 tests failed (155.12s)
Test suite chainweb-tests: FAIL
The most common error - **ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp**
(build-esential and netbase were installed, nix-build (Nix) 2.3.1)

`remote-golden:                                                              FAIL
          Exception: SendFailure "ConnectionError (HttpExceptionRequest Request {\n  host                 = \"127.0.0.1\"\n  port                 = 38369\n  secure               = True\n  requestHeaders       = [(\"Accept\",\"application/json;charset=utf-8,application/json\"),(\"Content-Type\",\"application/json;charset=utf-8\")]\n  path                 = \"/chainweb/0.0/fastTimedCPM-peterson/chain/8/pact/api/v1/send\"\n  queryString          = \"\"\n  method               = \"POST\"\n  proxy                = Nothing\n  rawBody              = False\n  redirectCount        = 10\n  responseTimeout      = ResponseTimeoutDefault\n  requestVersion       = HTTP/1.1\n}\n (ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp)))"`

**Comment by mightybyte** [comment]
This should be fixed now.
