### ISSUE TITLE
Build chainweb with nix and running a chainweb node

### ISSUE THREAD

**Issue by mdemir-bdt** [kadena-io/chainweb-node#76]
Following instructions in README I should be able to run chainweb node after building it with nix but I couldn't. The reason is `chainweb-node` executable is not there.

To run chainweb-node successfully: 

    ./result/ghc/chainweb/bin/chainweb-node --node-id=0 --config-file=./scripts/test-bootstrap-node.config

I am not sure if this is right the right executable.

**Comment by fosskers** [comment]
I'll have updated README instructions very soon.

**Comment by fosskers** [comment]
In the meantime, on my own machine I do have a `chainweb-node` here:
```
/home/colin/code/haskell/chainweb/result/ghc/chainweb/bin/chainweb-node
```

**Comment by fosskers** [comment]
Hi @mdemir-bdt , the README has been updated.
