### ISSUE TITLE
error while loading shared libraries: libtinfo.so.5

### ISSUE THREAD

**Issue by Shekelme** [kadena-io/chainweb-node#763]
I'm getting the following error message when I'm trying to start the chainweb-node:

`shekel@randomx1:~/kadena-chainweb$ ./chainweb-node --config-file=minimal-config.yaml                                                                      ./chainweb-node: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

Also, `ldd` shows the following:

```
shekel@randomx1:~/kadena-chainweb$ ldd chainweb-node
        linux-vdso.so.1 (0x00007fffc876d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc24ab1e000)
        libtinfo.so.5 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc24aafb000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc24aadf000)
        librocksdb.so.5.8 => not found
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc24aad4000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc24aacd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc24aac7000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fc24aa46000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc24a855000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc24ac77000)
```
How should I fix this? All [dependencies](https://github.com/kadena-io/chainweb-node/blob/master/README.md#linux-users) has been installed in advance. `libtinfo-dev` is also installed, so as `librocksdb-dev`.

OS: Ubuntu 19.10 Server

p.s. I have started chainweb-node by putting a "not found" libraries to /lib/x86_64-linux-gnu/ folder, but it's a brute force method...

**Comment by mightybyte** [comment]
The binaries we generate are built and meant to run on Ubuntu 18.04.  If you want to run on a different version, you'll probably need to build it yourself.  Our CI script is a good reference for how to do this:

https://github.com/kadena-io/chainweb-node/blob/master/.github/workflows/applications.yml#L62

**Comment by larskuhtz** [comment]
We currently only release binaries for Ubuntu LTS (18.04 and 16.04) and Mac OS X. If you think that we should also provide binaries for other OSes, feel free to file a new issue for it.
