### ISSUE TITLE
Discord invite in wiki is invalid

### ISSUE THREAD

**Issue by DarthVanger** [kadena-io/chainweb-node#764]
[Monitoring the health of a Chainweb Node](https://github.com/kadena-io/chainweb-node/wiki#monitoring-the-health-of-a-chainweb-node) section in wiki says:

>If you provide us with your ip address and port number in our Discord mining channel [...]

The Discord channel link is https://discordapp.com/invite/XPwzpj
When I open it, Discord says `Invite Invalid`.

<img width="645" alt="discord-invite-invalid" src="https://user-images.githubusercontent.com/6686679/69833287-7a277c80-123b-11ea-89a0-21ec87518300.png">

**Comment by mightybyte** [comment]
Fixed.  Thanks for the heads-up.
