### ISSUE TITLE
With new miner config authorized miners cant connect

### ISSUE THREAD

**Issue by MrAbaddon** [kadena-io/chainweb-node#804]
With new miner config and the private node, authorized miners cant connect.
I have in my yaml file:

databaseDirectory: /home/kadena/chainweb-db/
resetChainDatabases: false
chainweb:
  throttling:
    local: 0.1
    mining: 30
    global: 50.0
    putPeer: 11
  blockGasLimit: 100000
  chainwebVersion: mainnet01
  mining:
    coordination:
      enabled: true
      mode: public
      limit: 50000
      updateStreamLimit: 2000
      miners:
        - account: smartevolve
          predicate: keys-all
          public-keys:
          - 8a67d61c659bed41ee948513557886f041c50c336f284062197f4327fc4d990c
        - account: cloudinfo
          predicate: keys-all
          public-keys:
          - 09332cf0579b4862d59f519dd93015820987c8de4888e8e8691d01a1c3349ded
        - account: noncerpro
          predicate: keys-all
          public-keys:
          - 730f3ee4dc399aa5b343ad82cf4f9d7052f85911825abad40850bb9d92a3d5fd
    nodeMining:

But when miner tries to connect it receives:

Failed to get new job from kadena.smartevolve.com:443: Unauthorized Miner: 8a67d61c659bed41ee948513557886f041c50c336f284062197f4327fc4d990c

This is my private miner.

Thanks in advance

**Comment by mightybyte** [comment]
This is probably because you need to use your public key as the account.  It has to match whatever configuration you are using in your miner.  Some miners have you specify both the public key and account, but some miners automatically use the public key for both fields.

**Comment by MrAbaddon** [comment]
This has been tested and you are right. account should be the public key as I used the public key also for account name.
