### ISSUE TITLE
RPC API instruction

### ISSUE THREAD

**Issue by rlinxy** [kadena-io/chainweb-node#837]
We would like make a mining pool for Kadena, is there any instruction about the RPC interface? Such as getblocktemplate and submitblock etc... I went through the FAG and Wiki, but couldn't find one. Thanks.

**Comment by mightybyte** [comment]
The mining API is defined here:

https://github.com/kadena-io/chainweb-node/blob/master/src/Chainweb/Miner/RestAPI.hs#L47

There is also swagger documentation for it if you hit `/swagger.json`.

We have a standalone miner here https://github.com/kadena-io/chainweb-miner and the README has more in-depth documentation on mining with some info about the node's mining API.
