### ISSUE TITLE
How can i get mining work from chainweb-node?

### ISSUE THREAD

**Issue by duguyifang** [kadena-io/chainweb-node#847]
When I use the following method to get a mining task  from chainweb-node, it returns nothing. Can you give me some advice? i will be very appreciated.

```
curl -X GET  -sk   'https://127.0.0.1:3333/chainweb/0.0/mainnet01/mining/work?chain=1' -H "Content-type: application/json" -H "accept:application/json;blockheader-encoding=object"  -d'{"account": "5c1f0919dc0587fb80cfdeee9eabd3d25e186bb2dbfe1c5cb78bc84956166220", "predicate": "keys-all","public-keys": [ "5c1f0919dc0587fb80cfdeee9eabd3d25e186bb2dbfe1c5cb78bc84956166220"]}'
```
version : chainweb.8.6.5.ubuntu-18.04.b7d7faa9.tar.gz

**Comment by mightybyte** [comment]
The mining API is defined here:

https://github.com/kadena-io/chainweb-node/blob/master/src/Chainweb/Miner/RestAPI.hs#L47

There is also swagger documentation for it if you hit `/swagger.json`.

We have a standalone miner here https://github.com/kadena-io/chainweb-miner and the README has more in-depth documentation on mining with some info about the node's mining API.

**Comment by duguyifang** [comment]
thx! i have solved this problem using the following method :
```
curl -v --insecure  -H "Accept: application/octet-stream" -H "Content-type: application/json" -X GET -d '{"account":"minertest","predicate":"keys-all","public-keys":["d24b610a7d17eb873854735275f3da019a031ff6bd7fd2875ab1045d15bf3dc8"]}' 'https://127.0.0.1:3333/chainweb/0.0/testnet04/mining/work?chain=1'
```
