### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by larskuhtz** [kadena-io/chainweb-node#954]
The goal of this feature is to require that the first 8 bytes of the block header are set to zero for future use as feature flags.

* [x] Change CPU miners to use last 8 bytes as nonce and set first 8 bytes to 0
* [x] Switch nonce and feature flags in the binary serialization of the code
* [x] configure existing feature flag block header validation to enforce flag being 0
       (guarded by block height, I think, the guard may already exist)
* [x] work with pools and external miners to be aware of the change and adjust their software.

## Optional (possibly second PR):

* [x] improve performance of CPU miner by only iterating the final blake2s chunk (compress step) when searching for the nonce.

**Comment by mightybyte** [comment]
It might be a good idea to hold off merging these larger changes to master so we can keep master clear for intermediate releases if necessary.

@larskuhtz 
@slpopejoy

**Comment by larskuhtz** [comment]
Item (1.) and (2.) above are safe to merge. Item (3.) depends on (4.).

This can be released as soon as the big pools and miners set the first 8 bytes to 0. If we are certain that this will be the case when we release 1.7 we should merge to master now, in order to get test coverage. Otherwise we should not merge now.

I propose we do (1.) and (2.) and (4.). I think, (3.) would be a one line change that we can do whenever (4.) is complete.

**Comment by fosskers** [comment]
(1) is already in `master`. (2) is queued in https://github.com/kadena-io/chainweb-node/pull/960

**Comment by larskuhtz** [comment]
Just to confirm: #960 doesn't yet enforce the first 8 bytes to be zero? Is that right?

**Comment by fosskers** [comment]
Correct.
